@startuml

class WorkStation{
    - Buffer<Component>

    + WorkStation(Product)
    - tryProduce():boolean
    + run()
}

class Inspector{
    -Buffer<Component>
    -Buffer<Component>

    - Buffer(cmp1:Component, cmp2:Component)

    - getComponent()
    - returnBufferToFeed():int
    - feedBuffer()
    + run()

}

enum Component{
+ONE
+TWO
+THREE
}
enum Product{
+ONE
+TWO
+THREE
}



Component <- Inspector: creates
Product "1" <- "1" WorkStation
WorkStation ..> Component: uses

@enduml